name: Feature Request
about: Suggest new features to add
title: "[Feature]"
labels: ["feature", "template"]
assignees: ["dev-slife"]

body:
  - type: input
    id: name
    attributes:
      label: Feature Name
      description: A short name for the feature to help us understand your idea.
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of what your feature is.
    validations:
      required: true

  - type: textarea
    id: reason
    attriubtes:
      label: Reason For Feature
      description: A clear and concise reason as to why you believe this feature should be added.
    validations:
      required: true